import streamlit as st

##########################
# CSS #
##########################
st.markdown("""
    <style>
    /* Center all text elements */
    .block-container h1, 
    .block-container h2, 
    .block-container h3, 
    .block-container h4, 
    .block-container h5, 
    .block-container h6, 
    .block-container p {
        text-align: center;
    }
    /* Center the entire block container */
    .block-container {
        display: flex;
        flex-direction: column;
        align-items: center;   /* horizontal centering */
        justify-content: center; /* vertical centering */
    }

    /* Center the entire row of columns */
    div[data-testid="stHorizontalBlock"] {
        justify-content: center !important; /* center the row cluster */
        gap: 1rem !important;               /* optional spacing between buttons */
    }

    /* Optional: center buttons too */
    div.stButton {
        text-align: center;
    }       
    div.stButton > button {
        background-color: #00745d;   /* card color */
        color: white;                /* text color */
        border-radius: 10px;         /* rounded corners */
        height: 100px;               /* taller buttons */
        width: 100%;                 /* full column width */
        font-size: 18px;             /* larger text */
        font-weight: bold;
        transition: 0.3s;            /* smooth hover */
        margin: auto;
        display: block;
    }
    div.stButton > button:hover {
        background-color: #004234;   /* darker on hover */
        transform: scale(1.05);      /* slight zoom */
    }
    div[data-testid="stHorizontalBlock"] {
        gap: 0rem /* remove column gaps */
    }

    </style>
""", unsafe_allow_html=True)

st.set_page_config(
    page_title="Andrew Scheiner's Sports Dashboard",
    page_icon=":trophy:",
    layout="wide",
    initial_sidebar_state="expanded")

st.set_page_config(page_title="Andrew Scheiner's Sports Dashboard", page_icon=":trophy:", layout="wide")

st.title('Scheiner Sports Solutions')
st.markdown('An interactive Streamlit dashboard containing multiple sports solutions \
         for fantasy and betting help. Designed by Andrew Scheiner.')

##########################
#### Revamp home page ####
##########################
# Import each page as a module
import tools.NBABettingSystems as nba
import tools.NFLPowerRankings as nfl
import tools.PitcherProps as pitcher
import tools.TangoTracker as tango
import tools.LadderingTool as ladder
import tools.SlumpDetector as slump
import tools.ReverseRunYourPool as reverse_pool

# Initialize session state
if "page" not in st.session_state:
    st.session_state.page = "home"

# -------------------------------
# Betting Systems Section (3x1)
# -------------------------------
st.header("Betting Systems")
cols = st.columns(3)
if cols[0].button("⚾ Pitcher Props"):
    st.session_state.page = "pitcher"
if cols[1].button("🪜 Laddering Tool"):
    st.session_state.page = "ladder"
if cols[2].button("🏀 NBA Betting Systems"):
    st.session_state.page = "nba"

# -------------------------------
# Seasonal Tools Section (1x4)
# -------------------------------
st.header("Seasonal Tools")
cols2 = st.columns(4)
if cols2[0].button("🔍 Tango Tracker"):
    st.session_state.page = "tango"
if cols2[1].button("🏈 NFL Power Rankings"):
    st.session_state.page = "nfl"
if cols2[2].button("🧊 Slump Detector"):
    st.session_state.page = "slump"
if cols2[3].button("🔄 Reverse Run Your Pool"):
    st.session_state.page = "reverse_pool"

# Render selected page
if st.session_state.page == "nba":
    nba.app()
elif st.session_state.page == "nfl":
    nfl.app()
elif st.session_state.page == "pitcher":
    pitcher.app()
elif st.session_state.page == "tango":
    tango.app()
elif st.session_state.page == "ladder":
    ladder.app()
elif st.session_state.page == "slump":
    slump.app()
elif st.session_state.page == "reverse_pool":
    reverse_pool.app()
        
st.write("Data sources and packages: Fangraphs, pybaseball, nfl-data-py, MLB Stats API, Kaggle")
st.write("Disclaimer: I will not be displaying any lines posted by sportsbooks, and all predictions generated by my models are only recommendations. Please bet responsibly and only risk what you are willing to lose.")
st.write("© Andrew Scheiner 2025")