import streamlit as st

##########################
# CSS #
##########################
# Inject CSS to center all elements
st.markdown(
    """
    <style>
    .centered {
        display: flex;
        justify-content: center;
        align-items: center;
        text-align: center;
    }
    </style>
    """,
    unsafe_allow_html=True
)

# Wrap everything in a centered container
st.markdown('<div class="centered">', unsafe_allow_html=True)


st.set_page_config(
    page_title="Andrew Scheiner's Sports Dashboard",
    page_icon=":trophy:",
    layout="wide",
    initial_sidebar_state="expanded")

st.set_page_config(page_title="Andrew Scheiner's Sports Dashboard", page_icon=":trophy:", layout="wide")

st.title('Scheiner Sports Solutions')
st.markdown('An interactive Streamlit dashboard containing multiple sports solutions \
         for fantasy and betting help. Designed by Andrew Scheiner.')

##########################
#### Revamp home page ####
##########################
# Import each page as a module
import tools.NBABettingSystems as nba
import tools.NFLPowerRankings as nfl
import tools.PitcherProps as pitcher
import tools.TangoTracker as tango
import tools.LadderingTool as ladder
import tools.SlumpDetector as slump
import tools.ReverseRunYourPool as reverse_pool

# Initialize session state
if "page" not in st.session_state:
    st.session_state.page = "home"

# -------------------------------
# Betting Systems Section (3x1)
# -------------------------------
st.header("Betting Systems")
cols = st.columns(3)
if cols[0].button("⚾ Pitcher Props"):
    st.session_state.page = "pitcher"
if cols[1].button("🪜 Laddering Tool"):
    st.session_state.page = "ladder"
if cols[2].button("🏀 NBA Betting Systems"):
    st.session_state.page = "nba"

# -------------------------------
# Seasonal Tools Section (1x4)
# -------------------------------
st.header("Seasonal Tools")
cols2 = st.columns(4)
if cols2[0].button("🔍 Tango Tracker"):
    st.session_state.page = "tango"
if cols2[1].button("🏈 NFL Power Rankings"):
    st.session_state.page = "nfl"
if cols2[2].button("🧊 Slump Detector"):
    st.session_state.page = "slump"
if cols2[3].button("🔄 Reverse Run Your Pool"):
    st.session_state.page = "reverse_pool"

# Render selected page
if st.session_state.page == "nba":
    nba.app()
elif st.session_state.page == "nfl":
    nfl.app()
elif st.session_state.page == "pitcher":
    pitcher.app()
elif st.session_state.page == "tango":
    tango.app()
elif st.session_state.page == "ladder":
    ladder.app()
elif st.session_state.page == "slump":
    slump.app()
elif st.session_state.page == "reverse_pool":
    reverse_pool.app()

# Close the centered container
st.markdown('</div>', unsafe_allow_html=True)
        
st.write("Data sources and packages: Fangraphs, pybaseball, nfl-data-py, MLB Stats API, Kaggle")
st.write("Disclaimer: I will not be displaying any lines posted by sportsbooks, and all predictions generated by my models are only recommendations. Please bet responsibly and only risk what you are willing to lose.")
st.write("© Andrew Scheiner 2025")