import streamlit as st
from datetime import datetime
import pybaseball as pyb
import pandas as pd

st.title("🔍 Tango Tracker")
st.markdown("Track player movement, trends, and game-by-game performance shifts.")

##################################################
# Tango CY Young Tracker
##################################################
season = int(datetime.now().year)
def get_pitching_leaders(lg):
    #get 2024 pitching stat leaders for given league
    cy_young = pyb.pitching_stats(season,season,league=lg)
    #calculate tango cy young points
    cy_young["Tango"] = ((cy_young["IP"]/2) - cy_young["ER"]) + \
                        (cy_young["SO"]/10) + cy_young["W"]
    #get top 5 tango pitchers
    cy_young = cy_young.sort_values('Tango', ascending=False).reset_index(drop=True).head(5)
    #rank index 1-5
    cy_young.index = cy_young.index + 1

    #return tango DF
    return cy_young[["Name", "Tango", "Team", "W", "L", "GS", "IP", "SO", "ERA", "FIP", "WAR",  \
                     "xERA", "xFIP", "LOB%", "CG", "ShO"]]
st.subheader('AL Tango CY Young Tracker')
st.dataframe(get_pitching_leaders("AL"))
st.subheader('NL Tango CY Young Tracker')
st.dataframe(get_pitching_leaders("NL"))
##################################################

st.write("Data sources: Fangraphs, pybaseball, MLB Stats API, ")
st.write("Disclaimer: I will not be displaying any lines posted by sportsbooks, and all predictions generated by my models are only recommendations. Please bet responsibly and only risk what you are willing to lose.")
st.write("© Andrew Scheiner 2025")